services:
  db:
    image: postgres
    container_name: qflow-postgres
    environment:
      POSTGRES_DB: qflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    build: .
    container_name: qflow-app
    environment:
      DB_URL: jdbc:postgresql://db:5432/qflow
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: mysecretkey
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    # Se quiser otimizar o build, execute antes: gradlew build -x test
volumes:
  pgdata:
